# Generated by Django 5.2.11 on 2026-02-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='nota_professor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
