# Generated by Django 5.2.11 on 2026-02-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0002_trabalho_nota_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='nota_professor',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
