# Generated by Django 5.2.11 on 2026-02-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0003_remove_trabalho_nota_professor_trabalho_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='nota_professor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
